name: Test and Deploy

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-deploy.txt
        
    - name: Test imports
      run: |
        python -c "import streamlit; print('Streamlit import successful')"
        python -c "from streamlit_app import ASRSApp; print('Main app import successful')"
        python -c "import plotly; print('Plotly import successful')"
        python -c "import pandas; print('Pandas import successful')"
        
    - name: Basic syntax check
      run: |
        python -m py_compile streamlit_app.py
        python -m py_compile app.py
        
    - name: Check Streamlit app
      run: |
        streamlit run app.py --server.headless=true --server.port=8502 &
        sleep 10
        curl -f http://localhost:8502 || exit 1
        pkill -f streamlit
        
  notify:
    needs: test
    runs-on: ubuntu-latest
    if: always()
    
    steps:
    - name: Notify deployment status
      if: needs.test.result == 'success'
      run: |
        echo "✅ All tests passed! Ready for deployment to:"
        echo "- Streamlit Community Cloud"
        echo "- Hugging Face Spaces"
        echo "- Other cloud platforms"
        
    - name: Notify failure
      if: needs.test.result == 'failure'
      run: |
        echo "❌ Tests failed. Please fix issues before deployment."
        exit 1